bouquetapp/urls.py
from django.urls import path
from .views import *

app_name = "bouquetapp"

urlpatterns = [
    path('', home, name='home'),
    path('bouquets/form', bouquet_form, name='bouquet_form'),
    path('bouquets/<int:bouquet_id>/', bouquet_details, name='bouquet'),
]

flowershop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bouquetapp.urls'))
]

bouquetapp/models/bouquet.py
from django.db import models
from django.urls import reverse


class Bouquet(models.Model):

    name = models.CharField(max_length=100)
    occasion = models.CharField(max_length=100)
    flowers = models.ManyToManyField("Flower", through='BouquetFlower')

    class Meta:
        verbose_name = ("Bouquet")
        verbose_name_plural = ("Bouquets")

    def __str__(self):
        return f"{self.name} ({self.occasion})"

    def get_absolute_url(self):
        return reverse("Bouquet_detail", kwargs={"pk": self.pk})

bouquetapp/models/bouquet_flower.py
from django.db import models


class BouquetFlower(models.Model):

    flower = models.ForeignKey("Flower", on_delete=models.CASCADE)
    bouquet = models.ForeignKey("Bouquet", on_delete=models.CASCADE)
    quantity = models.IntegerField()

bouquetapp/models/flower.py
from django.db import models
from django.urls import reverse


class Flower(models.Model):

    name = models.CharField(max_length=100)
    binomial_name = models.CharField(max_length=100)
    longevity_in_days = models.IntegerField()
    bouquets = models.ManyToManyField("Bouquet", through='BouquetFlower')

    class Meta:
        verbose_name = ("Flower")
        verbose_name_plural = ("Flowers")

    def __str__(self):
        return f"{self.name} ({self.binomial_name})"

    def get_absolute_url(self):
        return reverse("Flower_detail", kwargs={"pk": self.pk})

bouquetapp/views/home.py
import sqlite3
from django.shortcuts import render
from bouquetapp.models import Bouquet
from .connection import Connection

def home(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            conn.row_factory = sqlite3.Row
            db_cursor = conn.cursor()

            db_cursor.execute("""
            SELECT
                b.id,
                b.name,
                b.occasion
            FROM bouquetapp_bouquet AS b
            ORDER BY b.name
            """)

            all_bouquets = []
            dataset = db_cursor.fetchall()

            for row in dataset:
                bouquet = Bouquet()
                bouquet.id = row['id']
                bouquet.name = row['name']
                bouquet.budget = row['occasion']

                all_bouquets.append(bouquet)

    template = 'home.html'
    context = {
        'bouquets': all_bouquets
    }

    return render(request, template, context)

bouquetapp/templates/bouquets/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bouquet</title>
  </head>
  <body>
    <h1>{{ info.name }}</h1>
    {% if info != ""%}
    <h2>For {{ info.occasion }}</h2>

    <div>Contains:</div>
    {%else%}
    <h2>This arrangment is still under construction</h2>
    {%endif%}
    {% for bouquet in bouquets %}
    {% if bouquet.quantity > 1%}
    <div>
    <span style="display: inline;">
    {{ bouquet.quantity }} {{ bouquet.flower_name }} Flowers 
    <form action="{% url 'bouquetapp:bouquet' bouquet.id  %}" style="display: inline;" method="POST">
    {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <input type="hidden" name="flower" value={{ bouquet.flower }}>
        <button>Delete</button>
    </form>
    </span>
    </div>
    {% else %}
    <div>
    <span style="display: inline;">
    {{ bouquet.quantity }} {{ bouquet.flower_name }} Flower 
    <form action="{% url 'bouquetapp:bouquet' bouquet.id  %}" style="display: inline;" method="POST">
    {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <input type="hidden" name="flower" value={{ bouquet.flower }}>
        <button>Delete</button>
    </form>
    </span>
    </div>
    {% endif %}
    {% endfor %}
  </body>
</html>

bouquetapp/templates/bouquets/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flower Shop</title>
  </head>
  <body>
    <h1>Create Bouquet</h1>


    <form action="{% url 'bouquetapp:bouquet_form' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="name">Name: </label>
          <input id="name" type="text" name="name">
      </fieldset>
      <fieldset>
          <label for="occasion">Occasion: </label>
          <input id="occasion" type="text" name="occasion">
      </fieldset>

      <input type="submit" value="Create" />
    </form>
  </body>
</html>

bouquetapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flower Shop</title>
  </head>
  <body>
    <h1>Our Bouquets</h1>
    <a href="{% url 'bouquetapp:bouquet_form' %}">Create New Bouquet</a>

    <ol>
    {% for bouquet in bouquets %}
        <li>
            <a href="{% url 'bouquetapp:bouquet' bouquet.id %}">{{ bouquet.name }}</a>
        </li>
    {% endfor %}
    </ol>
  </body>
</html>